name: Release StayAtScandinavia App Desktop Windows Microsoft Store

on:
  push:
    branches:
      - release/desktop-windows-microsoft-store
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.92

      - name: Install frontend dependencies
        run: pnpm install

      - name: Create .env file
        run: |
          touch .env
          echo GOOGLE_OAUTH_CLIENT_SECRET=${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }} >> .env
          echo GOOGLE_OAUTH_CLIENT_ID=${{ secrets.GOOGLE_OAUTH_CLIENT_ID }} >> .env
          cat .env

      - name: Build App
        run: |
          pnpm tauri build -c src-tauri/tauri.prod-windows-microsoftstore.conf.json
          # Move artifacts for code sign
          mkdir "${env:GITHUB_WORKSPACE}\src-tauri\target\release\bundle\to-sign"
          mkdir "${env:GITHUB_WORKSPACE}\src-tauri\target\release\bundle\signed"
          Move-Item "${env:GITHUB_WORKSPACE}\src-tauri\target\release\bundle\msi\*" "${env:GITHUB_WORKSPACE}\src-tauri\target\release\bundle\to-sign\" -Force
          Move-Item "${env:GITHUB_WORKSPACE}\src-tauri\target\release\bundle\nsis\*" "${env:GITHUB_WORKSPACE}\src-tauri\target\release\bundle\to-sign\" -Force
        shell: pwsh

      - name: Sign Artifact with CodeSignTool
        uses: sslcom/esigner-codesign@develop
        with:
          # CodeSignTool Commands:
          command: batch_sign
          username: ${{secrets.ES_USERNAME}}
          password: ${{secrets.ES_PASSWORD}}
          credential_id: ${{secrets.ES_CREDENTIAL_ID}}
          totp_secret: ${{secrets.ES_TOTP_SECRET}}
          # Path of code object to be signed.
          dir_path: ${GITHUB_WORKSPACE}\src-tauri\target\release\bundle\to-sign
          output_path: ${GITHUB_WORKSPACE}\src-tauri\target\release\bundle\signed
          # Scans your file for any possible malware in order to avoid code compromise and prevents signing of code if malware is detected.
          # On batch_sign command: If you are getting 'Error: hash needs to be scanned first before submitting for signing: <hash_value>', you can set this value to true
          malware_block: false
          # Clean log files after code signing operations
          clean_logs: true
          # Maximumx JVM heap size
          jvm_max_memory: 1024M
          # Code signing method. Default is v1. Supported values: v1, v2
          signing_method: v1

      - name: Extract version from tauri.prod-windows-microsoftstore.conf.json
        id: get_version
        shell: pwsh
        run: |
          $json = Get-Content src-tauri/tauri.prod-windows-microsoftstore.conf.json | ConvertFrom-Json
          echo "VERSION=$($json.version)" >> $env:GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: false
          body: "See the assets to download this version and install."
          name: "StayAtScandinavia App v${{ env.VERSION }} (Windows Microsoft Store)"
          files: |
            src-tauri/target/release/bundle/signed/*.msi
            src-tauri/target/release/bundle/signed/*.exe
